---
networkd:
  units:
    - name: 10-static.network
      contents: |
        [Match]
        Name=enp6s0

        [Network]
        Address=172.17.8.1/24
        Gateway=192.168.1.1
    - name: 20-dhcp.network
      contents: |
        [Match]
        Name=enp3s0f0

        [Network]
        DHCP=yes

systemd:
  units:
    - name: iptables-restore.service
      enable: true
    - name: lvm2-lvmetad.service
      enable: true
    - name: var-lib-rkt.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount volume for /var/lib/rkt
        Before=matchbox.service dnsmasq.service

        [Mount]
        What=/dev/matchbox-drewfus-org/var-lib-rkt
        Where=/var/lib/rkt
        Type=ext4

        [Install]
        WantedBy = multi-user.target
    - name: var-lib-docker.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount volume for /var/lib/docker
        Before=docker.service

        [Mount]
        What=/dev/matchbox-drewfus-org/var-lib-docker
        Where=/var/lib/docker
        Type=ext4

        [Install]
        WantedBy = multi-user.target
    - name: etc-matchbox.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount volume for /etc/matchbox
        Before=matchbox.service

        [Mount]
        What=/dev/matchbox-drewfus-org/etc-matchbox
        Where=/etc/matchbox
        Type=ext4

        [Install]
        WantedBy = multi-user.target
    - name: var-lib-matchbox.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount volume for /var/lib/matchbox
        Before=matchbox.service

        [Mount]
        What=/dev/matchbox-drewfus-org/var-lib-matchbox
        Where=/etc/matchbox
        Type=ext4

        [Install]
        WantedBy = multi-user.target
    - name: matchbox.service
      enable: true
      contents: |
        [Unit]
        Description=CoreOS matchbox Server
        Documentation=https://github.com/coreos/matchbox
        Requires=network-online.target
        After=network-online.target etc-matchbox.mount var-lib-matchbox.mount

        [Service]
        Slice=machine.slice
        KillMode=mixed
        Environment="IMAGE=quay.io/coreos/matchbox"
        Environment="VERSION=v0.6.1"
        Environment="MATCHBOX_ADDRESS=0.0.0.0:8080"
        Environment="MATCHBOX_RPC_ADDRESS=0.0.0.0:8081"
        Environment="MATCHBOX_LOG_LEVEL=debug"
        ExecStartPre=/usr/bin/mkdir -p /var/lib/matchbox/assets
        ExecStart=/usr/bin/rkt run \
          --net=host \
          --inherit-env \
          --trust-keys-from-https \
          --mount volume=data,target=/var/lib/matchbox \
          --mount volume=config,target=/etc/matchbox \
          --volume data,kind=host,source=/var/lib/matchbox \
          --volume config,kind=host,source=/etc/matchbox \
          ${IMAGE}:${VERSION}
        ExecStopPost=/usr/bin/rkt gc --mark-only
        Restart=always
        
        [Install]
        WantedBy=multi-user.target
    - name: etc-dnsmasq.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount volume for /etc/dnsmasq
        Before=dnsmasq.service

        [Mount]
        What=/dev/matchbox-drewfus-org/etc-dnsmasq
        Where=/etc/dnsmasq
        Type=ext4

        [Install]
        WantedBy = multi-user.target
    - name: var-lib-tftproot.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount volume for /var/lib/tftproot
        Before=dnsmasq.service

        [Mount]
        What=/dev/matchbox-drewfus-org/var-lib-tftproot
        Where=/var/lib/tftproot
        Type=ext4

        [Install]
        WantedBy = multi-user.target
    - name: dnsmasq.service
      enable: true
      contents: |
        [Unit]
        Description=dnsmasq
        # Wait for networking
        Requires=network-online.target
        After=network-online.target etc-dnsmasq.mount var-lib-tftproot.mount
        
        [Service]
        Slice=machine.slice
        KillMode=mixed
        Environment="IMAGE=quay.io/coreos/dnsmasq"
        Environment="VERSION=v0.4.1"
        ExecStartPre=/usr/bin/wget -nc -q -O "/var/lib/tftproot/undionly.kpxe" "http://boot.ipxe.org/undionly.kpxe"
        ExecStartPre=cp /var/lib/tftproot/undionly.kpxe /var/lib/tftproot/undionly.kpxe.0
        ExecStart=/usr/bin/rkt run \
          --hostname=matchbox.drewfus.org \
          --net=host \
          --inherit-env \
          --trust-keys-from-https \
          --volume etc-dnsmasq,kind=host,source=/etc/dnsmasq \
          --volume tftproot,kind=host,source=/var/lib/tftproot \
          --mount volume=etc-dnsmasq,target=/etc/dnsmasq \
          --mount volume=tftproot,target=/var/lib/tftproot \
          ${IMAGE}:${VERSION} \
          -- -d -C /etc/dnsmasq/dnsmasq.conf -R -S 8.8.8.8
        ExecStopPost=/usr/bin/rkt gc --mark-only
        Restart=always
        
        [Install]
        WantedBy=multi-user.target

storage:
  filesystems:
    - name: etc-dnsmasq
      mount:
        device: /dev/matchbox-drewfus-org/etc-dnsmasq
        format: ext4
    - name: etc-matchbox
      mount:
        device: /dev/matchbox-drewfus-org/etc-matchbox
        format: ext4
    - name: var-lib-docker
      mount:
        device: /dev/matchbox-drewfus-org/var-lib-matchbox
        format: ext4
    - name: var-lib-matchbox
      mount:
        device: /dev/matchbox-drewfus-org/var-lib-matchbox
        format: ext4
    - name: var-lib-rkt
      mount:
        device: /dev/matchbox-drewfus-org/var-lib-rkt
        format: ext4
    - name: var-lib-tftproot
      mount:
        device: /dev/matchbox-drewfus-org/var-lib-tftproot
        format: ext4
        
  files:
    - filesystem: root
      path: /etc/hostname
      mode: 0644
      contents:
        inline: matchbox.drewfus.org
    - filesystem: root
      path: /var/lib/iptables/rules-save
      mode: 0644
      contents:
        inline: |
          # Generated by iptables-save v1.4.21 on Mon Sep  4 18:17:44 2017
          *nat
          :PREROUTING ACCEPT [3:909]
          :INPUT ACCEPT [3:909]
          :OUTPUT ACCEPT [3:340]
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING -o enp3s0f0 -j MASQUERADE
          COMMIT
          # Completed on Mon Sep  4 18:17:44 2017
          # Generated by iptables-save v1.4.21 on Mon Sep  4 18:17:44 2017
          *filter
          :INPUT ACCEPT [836:58344]
          :FORWARD ACCEPT [0:0]
          :OUTPUT ACCEPT [666:162244]
          COMMIT
          # Completed on Mon Sep  4 18:17:44 2017
    - filesystem: etc-dnsmasq
      path: /etc/dnsmasq/dnsmasq.conf
      mode: 0644
      contents:
        inline: |
          interface=enp6s0
          dhcp-match=set:ipxe,175

          # if request comes from older PXE ROM, chainload to iPXE (via TFTP)
          dhcp-boot=tag:!ipxe,undionly.kpxe

          # point ipxe tagged requests to the matchbox iPXE boot script (via HTTP)
          dhcp-boot=tag:ipxe,http://matchbox.drewfus.org:8080/boot.ipxe

          # verbose
          log-queries
          log-dhcp

          enable-tftp
          tftp-root=/var/lib/tftproot

          dhcp-range=172.17.8.32,172.17.8.254,30m

          # static DNS assignements
          address=/matchbox.drewfus.org/172.17.8.1
          address=/core-1.drewfus.org/172.17.8.2
          address=/core-2.drewfus.org/172.17.8.3
          address=/core-3.drewfus.org/172.17.8.4

          # default GW [node need external access to fetch containers]
          dhcp-option=3,172.17.8.1

          # assign fixed hostname and ip address to the nodes
          #dhcp-host=00:50:56:20:AE:A6,core-1,172.17.8.2,infinite
          #dhcp-host=00:50:56:3C:0E:1A,core-2,172.17.8.3,infinite
          #dhcp-host=00:50:56:3C:0E:1A,core-3,172.17.8.4,infinite

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIEsyW+6KxtNl3iAjSrHeRSlZh3AnaWtDM7zO/G2dAAMl/fnYeWiFOAzYKOYC5crnK3U3CscY3IIy0HYNZ5TvIRNbzamn8bn7ThTw01QJJG0qH4xJ1w3qBtOWGC4xumMg1FXAg0Qa057jMsRkepWoqLfqSyJn6f9eJ1SqK6my8AKSoCxt6fgY8xNeNAXvODKkRLl2sf5h3dRPM7RvoGCr3KNraMsGRP7qI6sEoHlrMEz06rV8hm0+FtM2Nypxzjm505zAWwmvbhq79nGEGxONqyQJs/r7noSKYNZ6tq2r6qdtISebxg+pd5YQ7nX0vSdae+togYWrpVkRTkX66LScROGMVD1YSDHVfcQRKWvkO80HWvJuVWM8uWFsQIXTiC6NnP2Q5p+/RKYOQ1/5TewSYGlY+ErAiv8rxDXhs21S/rp80Fyd/hezKUs0fm0Te8gGZrYlVpieDHDf7q6Yp4zGCeA0nfzMYoaqDGwHeeg7KHQrY3kw66xu0VMa7x9tfgPGWjYY1z2Pb53dctd/PRI7GMmdZ1UVkvNJha2DdqGxh6kAH+idHZ9uF6PW2F7DecHCTipKEb64lHa2Bn8RUmJIN6gU1+YPZgA2nH75W2Y9QWwch5ekq+LA19atbZn6u6qTXx3pGJWKVmAg6p6ugJc1OJLPqkkKHkov5fhRcIrcMbQ== drew@Andrews-MacBook-Pro-2.local"
